# Generated by Django 4.2.17 on 2025-07-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0003_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
